name: PR Test Building Package for CentOS Stream 8

on:
  pull_request:
    paths:
    - 'build/centos-stream-8/**'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Build grub
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-grub2
      - name: Build shim package
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-shim
      - name: Build tdvf
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-tdvf
      - name: Build qemu-kvm
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-qemu-kvm
