name: PR Test Building SPR Kernel Package for CentOS Stream 8

on:
  pull_request:
    paths:
    - 'build/centos-stream-8/intel-mvp-spr-kernel/*'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Build tdx-guest-kernel 
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-spr-kernel
