name: Validate PR for Ubuntu-22.04 ovmf

on:
  pull_request:
    paths:
    - 'build/ubuntu-22.04/intel-mvp-ovmf/**'
  workflow_dispatch:

jobs:
  build_package:
    name: Build OVMF for Ubuntu 22.04
    runs-on: ubuntu-latest
    steps:
      - id: checkout_self
        name: Check out PR
        uses: actions/checkout@v3
      - id: build_ubuntu
        name: Build the source and binary packages
        run: |
          cd build/ubuntu-22.04/
          ./pkg-builder intel-mvp-ovmf/build.sh
