name: Validate PR for Ubuntu-22.04 amber-cli

on:
  pull_request:
    paths:
    - 'build/ubuntu-22.04/intel-mvp-amber-cli/**'
  workflow_dispatch:

jobs:
  build_package:
    name: Build amber-cli for Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - id: checkout_self
        name: Check out PR
        uses: actions/checkout@v3
      - id: build_ubuntu
        name: Build the source and binary packages
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --yes build-essential \
            fakeroot devscripts wget git equivs liblz4-tool sudo python-is-python3 pkg-config unzip
          cd build/ubuntu-22.04/intel-mvp-amber-cli/
          ./build.sh
